name: GitHub Actions Demo
on: [push]
jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.0.6
      - name: Terraform Init
        id: init
        run: terraform init
        working-directory: infrastructure/environments/dev
